### ISSUE TITLE
.env name

### ISSUE THREAD

**Issue by nicoska84** [Jean-Zombie/OpenAI-Usage-Monitor#1]
What should be the name of the .env config file that contains the api key?

**Comment by Jean-Zombie** [comment]
„.env“ should do it.

**Comment by nicoska84** [comment]
Thanks man! It worked 
![image](https://user-images.githubusercontent.com/73702791/235311930-000e46d5-d4c1-466c-98c7-e1e6115d9770.png)

**Comment by Jean-Zombie** [comment]
👍 sweet
